### ISSUE TITLE
stitch_params_path

### ISSUE THREAD

**Issue by ZQL666** [Kyle-Xu001/Multi-Depth-Multi-Camera-Stitching#1]
how can i get stitch_params？and what does the calib_params_mathe?hope your answer,thanks!

**Comment by Kyle-Xu001** [comment]
You can try the `stitch.py` to stitch two undistorted images by defining your own Range of Interests (ROIs). Calib_params are for the fisheye undistortion process. You may pass that if you use undistorted images.

**Comment by ZQL666** [comment]
If i want to get the real-time video stitching from multi-cameras（three or more）,how can i make it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kyle-Xu001/Multi-Depth-Multi-Camera-Stitching"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kyle-Xu001/Multi-Depth-Multi-Camera-Stitching] stitch_params_path (Issue #1)





 
You can try the stitch.py to stitch two undistorted images by defining your own Range of Interests (ROIs). Calib_params are for the fisheye undistortion process. You may pass that if you use undistorted images.

**Comment by Kyle-Xu001** [comment]
Estimate the homography matrix between two static images taken from the same frame. Then apply it to every frame taken from the video. Since I modify the class "ImageStitch" these days. I will modify the feature extraction and stitching between every two images accordingly in these days.

**Comment by ZQL666** [comment]
OKOK,thank you so much for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kyle-Xu001/Multi-Depth-Multi-Camera-Stitching"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kyle-Xu001/Multi-Depth-Multi-Camera-Stitching] stitch_params_path (Issue #1)





 
Estimate the homography matrix between two static images taken from the same frame. Then apply it to every frame taken from the video. Since I modify the class "ImageStitch" these days. I will modify the feature extraction and stitching between every two images accordingly in these days.
